In [1]:
import pandas as pd 
import numpy as np
import random

In [15]:
df = pd.read_csv("train.csv")
train = df
df.head()

age  gender  height  weight  ap_hi  ...  gluc  smoke  alco  active  cardio
0  17363       1     172    89.0    110  ...     1      0     1       0       0
1  21200       1     168    68.0    110  ...     1      0     0       1       0
2  17286       1     167    74.0    120  ...     1      0     0       1       0
3  15822       1     157    61.0     90  ...     1      0     0       1       0
4  20458       1     156    55.0    110  ...     1      0     0       1       0

[5 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   age          4000 non-null   int64  
 1   gender       4000 non-null   int64  
 2   height       4000 non-null   int64  
 3   weight       4000 non-null   float64
 4   ap_hi        4000 non-null   int64  
 5   ap_lo        4000 non-null   int64  
 6   cholesterol  4000 non-null   int64  
 7   gluc         4000 non-null   int64  
 8   smoke        4000 non-null   int64  
 9   alco         4000 non-null   int64  
 10  active       4000 non-null   int64  
 11  cardio       4000 non-null   int64  
dtypes: float64(1), int64(11)
memory usage: 375.1 KB


In [4]:
df['cardio'].value_counts(normalize=True)

0    0.505
1    0.495
Name: cardio, dtype: float64

In [5]:
df['cardio'].groupby(df['cholesterol']).mean()

cholesterol
1    0.432000
2    0.618692
3    0.759140
Name: cardio, dtype: float64

In [6]:
df['cardio'].groupby(df['ap_hi']).mean()

ap_hi
10       1.000000
11       0.666667
12       0.000000
13       0.000000
14       0.000000
           ...   
240      1.000000
1202     1.000000
1300     0.000000
1620     1.000000
14020    0.000000
Name: cardio, Length: 62, dtype: float64

In [7]:
df['cardio'].groupby(df['gender']).mean()

gender
1    0.493066
2    0.498575
Name: cardio, dtype: float64

In [8]:
df['cardio'].groupby(df['ap_lo']).mean()

ap_lo
0       0.000000
20      0.000000
40      1.000000
50      0.500000
60      0.222930
63      0.000000
65      0.500000
66      0.000000
68      0.000000
69      0.000000
70      0.273950
72      0.333333
73      1.000000
75      0.200000
77      1.000000
78      0.000000
79      0.571429
80      0.429768
82      1.000000
83      0.000000
84      0.000000
85      0.500000
87      0.666667
88      1.000000
89      1.000000
90      0.754717
94      1.000000
95      0.666667
96      1.000000
99      0.000000
100     0.807339
101     0.000000
103     0.000000
105     1.000000
109     1.000000
110     0.760000
115     1.000000
120     0.583333
130     0.666667
150     1.000000
710     0.000000
1000    0.886364
1001    1.000000
1100    0.909091
1110    1.000000
1120    1.000000
5700    0.000000
9800    0.000000
Name: cardio, dtype: float64

In [9]:
df['cardio'].groupby(df['gluc']).mean()

gluc
1    0.474816
2    0.600000
3    0.616129
Name: cardio, dtype: float64

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn import metrics


In [11]:
!pip3 install sklearn

In [14]:
def bootstrap(df, n):
    bob = df.sample(n)
    return bob


In [18]:
boots = bootstrap(train, 3)

In [19]:
boots

age  gender  height  weight  ap_hi  ...  gluc  smoke  alco  active  cardio
672   23410       1     157   110.0    150  ...     1      0     0       0       1
2148  18229       1     162    93.0    160  ...     1      0     0       0       1
646   14485       1     156    84.0    150  ...     1      0     0       1       1

[3 rows x 12 columns]

In [20]:
def randomforest(df, k, n, d):
    bootsy = bootstrap(df, n)
    t = bootsy.sample(d, axis = 1)
    features = list(t.columns)
    x = bootsy[features]
    bootsy.head()
    y = bootsy['cardio']
    classy = tree.DecisionTreeClassifier()
    classy = classy.fit(x,y)
    predicted = classy.predict(x)
    print("Accuracy:",metrics.accuracy_score(y, predicted))
    return predicted




In [21]:
bb = randomforest(train, 3, 3, 3)


Accuracy: 1.0


In [22]:
bb


array([0, 1, 0])

In [23]:
!pip3 install graphviz
!pip3 install pydotplus

In [24]:
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
from IPython.display import Image  
import pydotplus

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


In [26]:
test = pd.read_csv("test.csv")
n = 3
d = 3
k = 3
bootsy = bootstrap(df, n)
t = bootsy.sample(d, axis = 1)
features = list(t.columns)
x = bootsy[features]
bootsy.head()
y = bootsy['cardio']
classy = tree.DecisionTreeClassifier()
classy = classy.fit(x,y)
predicted = classy.predict(x)
dot_data = StringIO()
export_graphviz(classy, out_file=dot_data, filled=True, rounded=True,special_characters=True, feature_names=features,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('tree.png')
Image(graph.create_png())
print("Accuracy:",metrics.accuracy_score(y, predicted))


Accuracy: 1.0


In [28]:
train = pd.read_csv("train.csv")

In [29]:
train.head()

age  gender  height  weight  ap_hi  ...  gluc  smoke  alco  active  cardio
0  17363       1     172    89.0    110  ...     1      0     1       0       0
1  21200       1     168    68.0    110  ...     1      0     0       1       0
2  17286       1     167    74.0    120  ...     1      0     0       1       0
3  15822       1     157    61.0     90  ...     1      0     0       1       0
4  20458       1     156    55.0    110  ...     1      0     0       1       0

[5 rows x 12 columns]

In [30]:
X = train.iloc[:, 0:11].values
y = train.iloc[:, 11].values

In [32]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [39]:
from sklearn.ensemble import RandomForestClassifier

classylassy = RandomForestClassifier(n_jobs=20, random_state=0)
classylassy.fit(X, y)
y_pred = classylassy.predict(X)

In [40]:
y_pred

array([0, 0, 0, ..., 1, 1, 1])

In [41]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y, y_pred)))

Mean Absolute Error: 0.00025
Mean Squared Error: 0.00025
Root Mean Squared Error: 0.015811388300841896


In [42]:
print("Accuracy:",metrics.accuracy_score(y, y_pred))

Accuracy: 0.99975


In [43]:
test = pd.read_csv("test.csv")

In [46]:
X = test.iloc[:, 0:11].values
X

array([[0.0000e+00, 1.6036e+04, 1.0000e+00, ..., 2.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.0000e+00, 1.7004e+04, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.0000e+00, 1.7547e+04, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [9.9700e+02, 1.9673e+04, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        0.0000e+00],
       [9.9800e+02, 1.9662e+04, 2.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        0.0000e+00],
       [9.9900e+02, 1.8371e+04, 2.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [47]:
y_pred = classylassy.predict(X)

In [48]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,